ImmoWhatApp/ImmoWhatApp/Controllers/BienController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ImmoWhatApp.Controllers
{
    public class BienController : BaseController
    {
        // GET: Bien
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult AddNewBien()
        {
            try
            {
                List<Models.TypeBienModels> typesBiensList = new List<Models.TypeBienModels>
            {
                new Models.TypeBienModels{idTypeBien = 1, libelle = Resource.terrain},
                new Models.TypeBienModels{idTypeBien = 2, libelle = Resource.maison},
                new Models.TypeBienModels{idTypeBien = 3, libelle = Resource.villa},
                new Models.TypeBienModels{idTypeBien = 4, libelle = Resource.appartement}
            };

                List<Models.nbPieces> nbPieces = new List<Models.nbPieces>
            {
                new Models.nbPieces{qtite = 0, affiche = "0"},
                new Models.nbPieces{qtite = 1, affiche = "1"},
                new Models.nbPieces{qtite = 2, affiche = "2"},
                new Models.nbPieces{qtite = 3, affiche = "3"},
                new Models.nbPieces{qtite = 4, affiche = "4"},
                new Models.nbPieces{qtite = 5, affiche = "5"},
                new Models.nbPieces{qtite = 6, affiche = "6"},
                new Models.nbPieces{qtite = 7, affiche = "7"},
                new Models.nbPieces{qtite = 8, affiche = "8"},
                new Models.nbPieces{qtite = 9, affiche = "9"},
                new Models.nbPieces{qtite = 10, affiche = "10+"},
            };

                List<string> noteNRJ = new List<string> { "--", "A", "B", "C", "D", "E", "F", "G" };


                ViewBag.nrj = new SelectList(noteNRJ);
                ViewBag.nbPieces = new SelectList(nbPieces, "qtite", "affiche");
                ViewBag.ListeTypesBiens = new SelectList(typesBiensList, "idTypeBien", "libelle");
                return View();
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        public ActionResult AddNewBien(Models.BienModels monNvBien, List<HttpPostedFileBase> mesfichiers)
        {
            try
            {
                List<Models.TypeBienModels> typesBiensList = new List<Models.TypeBienModels>
            {
                new Models.TypeBienModels{idTypeBien = 1, libelle = Resource.terrain},
                new Models.TypeBienModels{idTypeBien = 2, libelle = Resource.maison},
                new Models.TypeBienModels{idTypeBien = 3, libelle = Resource.villa},
                new Models.TypeBienModels{idTypeBien = 4, libelle = Resource.appartement}
            };

                List<Models.nbPieces> nbPieces = new List<Models.nbPieces>
            {
                new Models.nbPieces{qtite = 0, affiche = "0"},
                new Models.nbPieces{qtite = 1, affiche = "1"},
                new Models.nbPieces{qtite = 2, affiche = "2"},
                new Models.nbPieces{qtite = 3, affiche = "3"},
                new Models.nbPieces{qtite = 4, affiche = "4"},
                new Models.nbPieces{qtite = 5, affiche = "5"},
                new Models.nbPieces{qtite = 6, affiche = "6"},
                new Models.nbPieces{qtite = 7, affiche = "7"},
                new Models.nbPieces{qtite = 8, affiche = "8"},
                new Models.nbPieces{qtite = 9, affiche = "9"},
                new Models.nbPieces{qtite = 10, affiche = "10+"},
            };

                List<string> noteNRJ = new List<string> { "--", "A", "B", "C", "D", "E", "F", "G" };

                ViewBag.nrj = new SelectList(noteNRJ);
                ViewBag.nbPieces = new SelectList(nbPieces, "qtite", "affiche");
                ViewBag.ListeTypesBiens = new SelectList(typesBiensList, "idTypeBien", "libelle");

                if (!ModelState.IsValid)
                {
                    return View(monNvBien);
                }
                Models.MembreModels monProfile = (Models.MembreModels)Session["moi"];
                monNvBien.idProprietaire = monProfile.idMembre;

                Models.RequestResultM resultRequest = BLL.BienBLL.addNewBien(monNvBien);

                if (resultRequest.result == "OK")
                {
                    return Json(new { success = true, responseText = resultRequest.msg }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(new { success = false, responseText = resultRequest.msg }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }

        }

        [HttpGet]
        public int GetIdBien(string codePostale, string rue, string numero, string boite)
        {
            try
            {
                Models.adresseModels adresse = new Models.adresseModels { CodePostal = codePostale, Numero = numero, Boite = boite, Rue = rue };
                int id = BLL.BienBLL.GetIdBien(adresse);
                return id;
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpPost]
        public ActionResult AddPhotoBien(string mesfichiers, int idBien, int numero)
        {
            try
            {
                List<string> listeImg = new List<string>();
                using (MemoryStream ms = new MemoryStream(Convert.FromBase64String(mesfichiers)))
                {
                    using (Bitmap bm2 = new Bitmap(ms))
                    {
                        string img = idBien + "-" + numero;
                        bm2.Save("C:/Users/thoma/OneDrive/EPHEC/TFE/immowhat-API/ImmoWhatApp/ImmoWhatApp/img/bien/" + img + ".jpg");
                        listeImg.Add(img);
                    }
                }
                Models.RequestResultM result = BLL.BienBLL.PostNewPhotos(idBien, listeImg);
                if (result.result == "OK")
                {
                    return Json(new { success = true, responseText = result.msg }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    // reagir si il y a eu un probleme
                    return Json(new { success = false, responseText = result.msg }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        [HttpGet]
        public JsonResult GetListBiensFromCPAndType(string codePostale, int type)
        {
            List<Models.BienModels> listeDeBiens = new List<Models.BienModels>();
            listeDeBiens = BLL.BienBLL.GetListBiensFromCPAndType(codePostale, type);

            return Json(new { result = "OK", listeBiens = listeDeBiens }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult voirLeBien(int idBien)
        {
            Models.BienModels TheBien = new Models.BienModels();

            TheBien = BLL.BienBLL.GetOneBien(idBien);
            ViewBag.typeBien = TheBien.typeBien;

            return View(TheBien);
        }

        [HttpGet]
        public ActionResult voirMonBien(int idBien)
        {
            Models.BienModels TheBien = new Models.BienModels();

            TheBien = BLL.BienBLL.GetOneBien(idBien);
            ViewBag.typeBien = TheBien.typeBien;

            return View(TheBien);
        }

        [HttpGet]
        public ActionResult _MesBiensListe(int idMembre)
        {
            try
            {
                List<Models.BienModels> listeDeBiens = new List<Models.BienModels>();
                listeDeBiens = BLL.BienBLL.GetMyBiensList(idMembre);

                ViewBag.idMembre = idMembre;

                return PartialView(listeDeBiens);
            }
            catch (Exception ex)
            {
                throw ex;
            }

        }

        [HttpPost]
        public JsonResult DeleteBienByUser(int idBien)
        {
            Models.RequestResultM resultRequest = new Models.RequestResultM();

            resultRequest = BLL.BienBLL.DeleteBienByUser(idBien);

            return Json(new { result = "OK", res = resultRequest });



        }

        [HttpPost]
        public Models.RequestResultM DeleteBienByAdmin(int idBien)
        {
            Models.RequestResultM resultRequest = new Models.RequestResultM();

            resultRequest = BLL.BienBLL.DeleteBienByAdmin(idBien);

            return resultRequest;



        }

        [HttpPost]
        public JsonResult DeclareBienAsVendu(int idBien)
        {
            Models.RequestResultM resultRequest = new Models.RequestResultM();

            resultRequest = BLL.BienBLL.DeclareBienAsVendu(idBien);

            return Json(new { result = "OK", res = resultRequest });



        }

        public ActionResult _GetAllBiens(string recherche)
        {
            List<Models.RechercheBienModels> lesBiens = BLL.BienBLL.SearchBien(recherche);
            int nbBiensSupp = lesBiens.FindAll(e => e.deleted == true).Count;
            int nbBiensVendus = lesBiens.FindAll(e => e.vendu == true).Count;
            int nbBienEnACT = lesBiens.Count - nbBiensSupp - nbBiensVendus;

            ViewBag.nbBiensSupp = nbBiensSupp;
            ViewBag.nbBiensVendus = nbBiensVendus;
            ViewBag.nbBienEnACT = nbBienEnACT;

            return PartialView(lesBiens);
        }
    }
}

ImmoWhatApp/ImmoWhatApp/Views/Bien/_GetAllBiens.cshtml
@model IEnumerable<ImmoWhatApp.Models.RechercheBienModels>

<table class="table">
    <thead>
        <tr class="d-table-row" style="text-align:center">
            <th class="d-table-cell" style="vertical-align:middle">@Html.DisplayNameFor(model => model.idBien)</th>
            <th class="d-table-cell" style="vertical-align:middle">@Resource.proprietaire</th>
            <th class="d-table-cell" style="vertical-align:middle">@Html.DisplayNameFor(model => model.commune)</th>
            <th class="d-table-cell" style="vertical-align:middle">@Html.DisplayNameFor(model => model.codePostal)</th>
            <th class="d-table-cell" style="vertical-align:middle">@Html.DisplayNameFor(model => model.rue)</th>
            <th class="d-table-cell" style="vertical-align:middle"> @Html.DisplayNameFor(model => model.numero)</th>
            <th class="d-table-cell" style="vertical-align:middle">@Html.DisplayNameFor(model => model.prix)</th>
            <th></th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            if (item.deleted == true)
            {
                <tr class="deleted table-danger d-table-row" style="text-align:center; vertical-align: middle; ">
                    <td class="d-table-cell align-self-center" style="vertical-align:middle">@Html.DisplayFor(modelItem => item.idBien)</td>
                    <td class="d-table-cell align-self-center" style="vertical-align:middle">@Html.DisplayFor(modelItem => item.nom)<br />@Html.DisplayFor(modelItem => item.prenom) </td>
                    <td class="d-table-cell align-self-center" style="vertical-align:middle">@Html.DisplayFor(modelItem => item.commune)</td>
                    <td class="d-table-cell align-self-center" style="vertical-align:middle">@Html.DisplayFor(modelItem => item.codePostal)</td>
                    <td class="d-table-cell align-self-center" style="vertical-align:middle">@Html.DisplayFor(modelItem => item.rue)</td>
                    @{
                        if (item.boite == "-1")
                        {
                            <td class="d-table-cell align-self-center" style="vertical-align:middle">@Html.DisplayFor(modelItem => item.numero)</td>
                        }
                        else
                        {
                            <td class="d-table-cell align-self-center" style="vertical-align:middle">@Html.DisplayFor(modelItem => item.numero)  bte @Html.DisplayFor(modelItem => item.boite)</td>
                        }
                    }

                    <td class="d-table-cell align-self-center" style="vertical-align:middle">@Html.DisplayFor(modelItem => item.prix)</td>
                    <td class="d-table-cell align-self-center" style="vertical-align:middle">
                        <button id="@item.idBien" style="height:60px; width:60px" class="tooltipT btnVoirBien btn btn-light rounded-circle" type="button"><img src="https://png.icons8.com/ios/40/000000/detective.png"><span class="tooltiptext">@Resource.voirLeBien</span></button>
                        <button id="@item.idBien" style="height:60px; width:60px" class="tooltipT btnSupprimerBien btn btn-danger rounded-circle" type="button"><img src="https://png.icons8.com/ios/35/000000/trash.png"><span class="tooltiptext">@Resource.supprimer</span></button>
                    </td>
                </tr>
            }
            else if (item.vendu == true)
            {
                <tr class="vendu table-success d-table-row" style="text-align:center; vertical-align: middle">
                    <td class="d-table-cell align-self-center" style="vertical-align:middle">@Html.DisplayFor(modelItem => item.idBien)</td>
                    <td class="d-table-cell align-self-center" style="vertical-align:middle">@Html.DisplayFor(modelItem => item.nom)<br />@Html.DisplayFor(modelItem => item.prenom) </td>
                    <td class="d-table-cell align-self-center" style="vertical-align:middle">@Html.DisplayFor(modelItem => item.commune)</td>
                    <td class="d-table-cell align-self-center" style="vertical-align:middle">@Html.DisplayFor(modelItem => item.codePostal)</td>
                    <td class="d-table-cell align-self-center" style="vertical-align:middle">@Html.DisplayFor(modelItem => item.rue)</td>
                    @{
                        if (item.boite == "-1")
                        {
                            <td class="d-table-cell align-self-center" style="vertical-align:middle">@Html.DisplayFor(modelItem => item.numero)</td>
                        }
                        else
                        {
                            <td class="d-table-cell align-self-center" style="vertical-align:middle">@Html.DisplayFor(modelItem => item.numero)  bte @Html.DisplayFor(modelItem => item.boite)</td>
                        }
                    }

                    <td class="d-table-cell align-self-center" style="vertical-align:middle">@Html.DisplayFor(modelItem => item.prix)</td>
                    <td class="d-table-cell align-self-center" style="vertical-align:middle">
                        <button id="@item.idBien" style="height:60px; width:60px" class="tooltipT btnVoirBien btn btn-light rounded-circle" type="button"><img src="https://png.icons8.com/ios/40/000000/detective.png"><span class="tooltiptext">@Resource.voirLeBien</span></button>
                        <button id="@item.idBien" style="height:60px; width:60px" class="tooltipT btnSupprimerBien btn btn-danger rounded-circle" type="button"><img src="https://png.icons8.com/ios/35/000000/trash.png"><span class="tooltiptext">@Resource.supprimer</span></button>
                    </td>
                </tr>
            }
            else
            {
                <tr class="enVente d-table-row" style="text-align:center; vertical-align: middle">
                    <td class="d-table-cell align-self-center" style="vertical-align:middle">@Html.DisplayFor(modelItem => item.idBien)</td>
                    <td class="d-table-cell align-self-center" style="vertical-align:middle">@Html.DisplayFor(modelItem => item.nom)<br />@Html.DisplayFor(modelItem => item.prenom) </td>
                    <td class="d-table-cell align-self-center" style="vertical-align:middle">@Html.DisplayFor(modelItem => item.commune)</td>
                    <td class="d-table-cell align-self-center" style="vertical-align:middle">@Html.DisplayFor(modelItem => item.codePostal)</td>
                    <td class="d-table-cell align-self-center" style="vertical-align:middle">@Html.DisplayFor(modelItem => item.rue)</td>
                    @{
                        if (item.boite == "-1")
                        {
                            <td class="d-table-cell align-self-center" style="vertical-align:middle">@Html.DisplayFor(modelItem => item.numero)</td>
                        }
                        else
                        {
                            <td class="d-table-cell align-self-center" style="vertical-align:middle">@Html.DisplayFor(modelItem => item.numero)  bte @Html.DisplayFor(modelItem => item.boite)</td>
                        }
                    }

                    <td class="d-table-cell align-self-center" style="vertical-align:middle">@Html.DisplayFor(modelItem => item.prix)</td>
                    <td class="d-table-cell align-self-center" style="vertical-align:middle">
                        <button id="@item.idBien" style="height:60px; width:60px" class="tooltipT btnVoirBien btn btn-light rounded-circle" type="button"><img src="https://png.icons8.com/ios/40/000000/detective.png"><span class="tooltiptext">@Resource.voirLeBien</span></button>
                        <button id="@item.idBien" style="height:60px; width:60px" class="tooltipT btnSupprimerBien btn btn-danger rounded-circle" type="button"><img src="https://png.icons8.com/ios/35/000000/trash.png"><span class="tooltiptext">@Resource.supprimer</span></button>
                    </td>
                </tr>
            }

        }
    </tbody>
</table>

<input id="nbBiensSupprimes" value='@ViewBag.nbBiensSupp' style="display:none" />
<input id="nbBiensVend" value='@ViewBag.nbBiensVendus' style="display:none" />
<input id="nbBienEnACTion" value='@ViewBag.nbBienEnACT' style="display:none" />

<script>

    $('.btnVoirBien').click(function () {
        var idBien = $(this).attr("id");

        var url = "../Bien/voirMonBien?idBien=" + idBien;
        window.location.href = url;
    });

     $('.btnSupprimerBien').click(function () {
        //$('#chargement').show();

         var id = $(this).attr("id");
        $('#modalDeleteTxt').html("Etes vous sure de vouloir supprimer définitivement ce bien?");

        $('#modal_delete').dialog({
            open: function (event, ui) { $(".ui-dialog-titlebar-close").hide(); },
            resizable: false,
            height: "auto",
            width: "400",
            modal: true,
            title: "ATTENTION",

            buttons: {
                "oui": function () {
                    $.ajax({
                        type: 'POST',
                        data: { idBien: id },
                        url: '@Url.Action("DeleteBienByAdmin", "Bien")',
                        success: function (donnee) {

                            $('#modalTxt').html("Bien supprimé avec succès!");

                            $('#modal_info').dialog({
                                open: function (event, ui) { $(".ui-dialog-titlebar-close").hide(); },
                                resizable: false,
                                height: "auto",
                                width: "400",
                                modal: true,
                                title: "bravo!",
                                buttons: {
                                    "ok": function () {
                                        window.location = '@Url.Action("AdminPage", "Home")';
                                    }
                                }
                            });



                        },
                        error: function (donnee) {
                            alert("probleme : " + donnee.status + "\n" + donnee.responseText);
                        }
                    });


                },
                "non": function () {
                    $(this).dialog("close");
                }
            }
        });

    });

    $(document).ready(function () {



        //if ($('#Biendeleted').checked) {
        //    $('.deleted').addClass("d-table-row")
        //    $('.deleted').removeClass("d-none")
        //}
        //else {
        //    $('.deleted').removeClass("d-table-row")
        //    $('.deleted').addClass("d-none")
        //}

        //if ($('#vendu').checked) {
        //    $('.vendu').addClass("d-table-row")
        //    $('.vendu').removeClass("d-none")
        //}
        //else {
        //    $('.vendu').removeClass("d-table-row")
        //    $('.vendu').addClass("d-none")
        //}

        //if ($('#BiensEnVente').checked) {
        //    $('.enVente').addClass("d-table-row")
        //    $('.enVente').removeClass("d-none")
        //}
        //else {
        //    $('.enVente').removeClass("d-table-row")
        //    $('.enVente').addClass("d-none")
        //}

    });


</script>

ImmoWhatApp/ImmoWhatApp/Views/Bien/_MesBiensListe.cshtml
@model IEnumerable<ImmoWhatApp.Models.BienModels>


<div class="row mt-5" style="margin:1px;">
    <div class="col">
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                    <tr style="width:100%;">
                        <th class="align-middle" style="width:5%;"> @Html.DisplayNameFor(model => model.estVendu)</th>
                        <th class="align-middle" style="width:10%;"> @Html.DisplayNameFor(model => model.typeBien)</th>
                        <th class="align-middle" style="width:40%;">adresse</th>
                        <th class="align-middle" style="width:15%;"></th>
                        <th class="align-middle" style="width:30%;"></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        string adresse = "";
                        string btnVendu = "vendu" + item.idBien;
                        string urlImg = "/img/bien/" + item.idBien + "-0.jpg";
                        if (item.boite == "-1")
                        {
                            adresse = item.numero + " " + item.rue + "\n" + item.codePostale + " " + item.commune;
                        }
                        else
                        {
                            adresse = item.numero + " " + item.rue + " bte " + item.boite + "\n" + item.codePostale + " " + item.commune;
                        }

                        <tr>
                            @if (item.estVendu == true)
                            {
                                <td class="align-middle"><img src="~/img/logos/checkbox-true.png" style="width:40px;height:40px;"></td>
                            }
                            else
                            {
                                <td class="align-middle"><img src="~/img/logos/checkbox-false.png" style="width:40px;height:40px;"></td>
                            }

                            @switch (item.typeBien)
                            {
                                case 1:
                                    <td class="align-middle">@Resource.terrain</td>
                                    break;
                                case 2:
                                    <td class="align-middle">@Resource.maison</td>
                                    break;
                                case 3:
                                    <td class="align-middle">@Resource.villa</td>
                                    break;
                                case 4:
                                    <td class="align-middle">@Resource.appartement</td>
                                    break;
                                default:
                                    <td class="align-middle">@Resource.maison</td>
                                    break;
                            }

                            <td class="align-middle"><span style="white-space:pre-line">@adresse</span></td>
                            <td class="align-middle"><img src='@urlImg' style="max-width:120px;max-height:120px;"></td>
                            <td style="text-align:end" class="align-middle">
                                @if (item.estVendu == false)
                                {
                                    <button value="@item.idBien" style="height:60px; width:60px" class="tooltipL btnVendu btn btn-success rounded-circle" type="button"><img src="https://png.icons8.com/windows/40/000000/handshake.png"><span class="tooltiptext">pour mettre le bien comme vendu</span></button>
                                }
                                <button value="@item.idBien" style="height:60px; width:60px" class="tooltipT tooltiptt btnModifier btn btn-warning rounded-circle" type="button"><img src="https://png.icons8.com/ios/40/000000/hand-with-pen.png"><span class="tooltiptext">modifier</span></button>
                                <button value="@item.idBien" style="height:60px; width:60px" class="tooltipT btnVoirBien btn btn-light rounded-circle" type="button"><img src="https://png.icons8.com/ios/40/000000/detective.png"><span class="tooltiptext">voir le bien</span></button>
                                <button value="@item.idBien" style="height:60px; width:60px" class="tooltipT btnSupprimerBien btn btn-danger rounded-circle" type="button"><img src="https://png.icons8.com/ios/35/000000/trash.png"><span class="tooltiptext">@Resource.supprime</span></button>
                            </td>


                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<script>



    $('.btnVendu').click(function () {
        var idBien = $(this).attr("value");


        $('#modalTxt').html("confirmer vous que ce bien a été vendu?");

        $('#modal_info').dialog({
            open: function (event, ui) { $(".ui-dialog-titlebar-close").hide(); },
            resizable: false,
            height: "auto",
            width: "400",
            modal: true,
            title: "ATTENTION",

            buttons: {
                "oui": function () {
                    $(this).dialog("close");
                    $.ajax({
                        type: 'POST',
                        datatype: 'json',
                        url: '@Url.Action("DeclareBienAsVendu", "Bien")',
                        data: { "idBien": idBien },
                        success: function (donnee) {
                            if (donnee.res.result == "OK") {

                                $('#modalFelicitationsTxt').html("Félicitations pour la vente de votre bien!");

                                $('#modal_Felicitations').dialog({
                                    open: function (event, ui) { $(".ui-dialog-titlebar-close").hide(); },
                                    resizable: false,
                                    height: "auto",
                                    width: "400",
                                    modal: true,
                                    title: "Congratulation",

                                    buttons: {
                                        "ok": function () {
                                            GetListBiens(@ViewBag.idMembre);
                                            $(this).dialog("close");
                                        }

                                    }
                                });

                            }
                            else {
                                alert("ca n a pas marché... pq???")
                            }


                        },
                        error: function (error) {

                            alert(error.text);
                        }
                    });


                },
                "non": function () {
                    $(this).dialog("close");
                }
            }
        });

    });
    $('.btnModifier').click(function () {
        alert($(this).attr("value"));
    })
    $('.btnVoirBien').click(function () {
        var idBien = $(this).attr("value");

        var url = "../Bien/voirMonBien?idBien=" + idBien;
        window.location.href = url;
    });
    $('.btnSupprimerBien').click(function () {
        var idBien = $(this).attr("value");

        $('#modalDeleteTxt').html("Etes vous sure de vouloir supprimer ce bien?");

        $('#modal_delete').dialog({
            open: function (event, ui) { $(".ui-dialog-titlebar-close").hide(); },
            resizable: false,
            height: "auto",
            width: "400",
            modal: true,
            title: "ATTENTION",

            buttons: {
                "oui": function () {
                    $(this).dialog("close");
                    $.ajax({
                        type: 'POST',
                        datatype: 'json',
                        url: '@Url.Action("DeleteBienByUser", "Bien")',
                        data: { "idBien": idBien },
                        success: function (donnee) {
                            if (donnee.res.result == "OK") {
                                GetListBiens(@ViewBag.idMembre);
                            }
                            else {
                                alert("ca n a pas marché... pq???")
                            }


                        },
                        error: function (error) {

                            alert(error.text);
                        }
                    });


                },
                "non": function () {
                    $(this).dialog("close");
                }
            }
        });


    });

    function GetListBiens(idMembre) {
         $.ajax({
            type: 'GET',
            datatype: 'json',
            url: '@Url.Action("_MesBiensListe", "Bien")',
            data: { "idMembre": idMembre },
            success: function (donnee) {
                    $('#PartialViewTableBiens').html(donnee);


            },
            error: function (error) {

                alert(error.text);
            }
        });
    }


</script>



<script src="~/Scripts/popper.min.js"></script>